Fix copying behavior of properties when resubmitting messages
paolosalvatori/ServiceBusExplorer pull request #370
Opened 2019-08-05 22:48 UTC by gabrielgt

When resubmitting several messages in batch mode, properties should be copied when cloning. But when resubmitting only one message, properties should not, because the user can choose what properties he wants to copy through Message Custom Properties GroupBox.

   ![image](https://user-images.githubusercontent.com/3408827/62499629-a7ab6e80-b7e3-11e9-8233-8fa27792750e.png)

So, clone depends on resubmitting one or more messages.
In any case, properties with name "DeadLetterReason", "DeadLetterErrorDescription" and "NServiceBus.Transport.Recovery", should never be copied.

Issue #344 should be solved with this PR.

2019-08-05 22:49 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0370.119.build.586 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/26489182) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9384058b5f by @gabrielgt)

2020-01-17 11:02 UTC, paolosalvatori commented
Hi @gabrielgt I approved the PR, but it has conflicts that must be resolved.

2020-03-20 00:18 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-develop-properties.59.build.657 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31591247) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/039ba3d89d by @gabrielgt)

2020-03-20 00:21 UTC, gabrielgt commented
Hi @paolosalvatori, I have resolved the conflicts. Sorry for the delay.

2020-11-13 23:04 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-develop-properties.79.build.730 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36304218) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/a6b294cfd8 by @gabrielgt)

2020-11-13 23:19 UTC, gabrielgt commented
I have resolved the conflicts again, please review the PR.

2020-11-14 20:13 UTC, SeanFeldman requested changes

2020-11-14 20:13 UTC, SeanFeldman commented on src/Common/Helpers/Constants.cs
> +        public static readonly List<string> AlwaysOmittedProperties = new List<string> {"deadletterreason", "deadlettererrordescription", "nservicebus.transport.recovery"};
I'm on a fence about this. When someone else adds a property to be excluded and they copy the property here, they have to remember to lower case it or else it won't work.
I'd rather see headers used as they are defined (provided).

2020-11-14 20:13 UTC, SeanFeldman commented on src/Common/Helpers/BrokeredMessageExtensions.cs
> +                var propertiesToCopy = originalMessage.Properties.Where(h => !Constants.AlwaysOmittedProperties.Contains(h.Key.ToLower()));
We'd be safer to compare using `StringComparer.InvariantCultureIgnoreCase`. That way there's no need for special treatment neither of the excluded header values nor all message property names.

2020-11-15 19:06 UTC, SeanFeldman commented
:x: [Build ServiceBusExplorer 4.2.0-develop-properties.80.build.731 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36322382) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/af38ea9de4 by @)

2020-11-15 19:09 UTC, gabrielgt commented on src/Common/Helpers/Constants.cs
> +        public static readonly List<string> AlwaysOmittedProperties = new List<string> {"deadletterreason", "deadlettererrordescription", "nservicebus.transport.recovery"};
I agree. Changed to pascal case.

2020-11-15 19:10 UTC, gabrielgt commented on src/Common/Helpers/BrokeredMessageExtensions.cs
> +                var propertiesToCopy = originalMessage.Properties.Where(h => !Constants.AlwaysOmittedProperties.Contains(h.Key.ToLower()));
Changed for a comparison with InvariantCultureIgnoreCase in BrokeredMessageExtensions.cs and MessageForm.cs.

2020-11-15 19:15 UTC, SeanFeldman commented
:x: [Build ServiceBusExplorer 4.2.0-develop-properties.80.build.732 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36322437) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/af38ea9de4 by @)

2020-11-16 04:38 UTC, SeanFeldman commented
@gabrielgt the build is failing but doesn't seem like it's the change in this PR. I'll look into that tomorrow as I'd like to include this fix in 5.0.0.

2020-11-23 08:53 UTC, paolosalvatori commented
Hi @SeanFeldman does the build succeed now? Can I proceed and approve this PR? Thanks

2020-11-23 22:57 UTC, SeanFeldman commented
@paolosalvatori, it doesn't, and I'm confused why that's the case. It builds fine locally.

@gabrielgt, do you mind to open an alternative PR to see if that fixes it? Let's try fixing the PR build so that it can be included in the v5 release.

2020-11-24 20:27 UTC, gabrielgt commented
@SeanFeldman did it, and it worked!! 😲

2020-11-24 20:32 UTC, ErikMogensen approved these changes
Nice!

2020-11-24 21:04 UTC, SeanFeldman approved these changes

2020-11-24 21:07 UTC, merged

2020-11-25 07:59 UTC, paolosalvatori commented
Thanks folks :)