Add coloring feature to nodes
paolosalvatori/ServiceBusExplorer pull request #468
Opened 2020-10-02 11:33 UTC by Greybird

The purpose of this PR is to allow configuring colors for nodes (either leaves or intermediate "directories") based on regular expressions.

# Screenshots
## Configuration
![image](https://user-images.githubusercontent.com/8553578/94918810-9a574600-04b3-11eb-9dee-4079cc038127.png)

## Results
![image](https://user-images.githubusercontent.com/8553578/94918266-83642400-04b2-11eb-9d4f-4a3ee7fb9f4a.png)

2020-10-02 11:35 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-colors.71.build.712 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35532445) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/a8d06c0b75 by @)

2020-10-02 11:47 UTC, ekaliroots commented
Nice feature, we may add style like bold on populated queues too

2020-10-02 12:52 UTC, SeanFeldman submitted a review, later dismissed
Thank you, @Greybird !

2020-10-02 16:14 UTC, ErikMogensen requested changes
Awesome feature!

Just that minor casing issue.

2020-10-02 16:14 UTC, ErikMogensen commented on src/ServiceBusExplorer/Forms/MainForm.cs
> +        void ReApplyColors(TreeNode parentNode)
A picky comment : Reapply instead of ReApply since reapply is a word in itself.

2020-10-02 17:49 UTC, Greybird commented on src/ServiceBusExplorer/Forms/MainForm.cs
> +        void ReApplyColors(TreeNode parentNode)
Thanks for pointing this, I learned something 👍 !

2020-10-02 17:49 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-colors.72.build.713 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35539755) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/d3be126f00 by @)

2020-10-03 09:35 UTC, ErikMogensen submitted a review, later dismissed

2020-10-05 19:13 UTC, ErikMogensen commented
@Greybird, I merged the other PR, which you said could adapt. I hope you can fix this PR instead.

@SeanFeldman, apparently you have to approve again when there has been changes to the PR. I think that is new behavior.

2020-10-05 19:17 UTC, SeanFeldman commented
@ErikMogensen, no worries. I'll let @Greybird address this PR and then re-approve it so that there's no need to do it a 3rd time 😀

2020-10-05 19:38 UTC, ErikMogensen commented
Sounds good @SeanFeldman 😃

2020-10-06 19:19 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-colors.74.build.717 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35603247) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/de7d1f15ff by @)

2020-10-06 19:20 UTC, Greybird commented
> @Greybird, I merged the other PR, which you said could adapt. I hope you can fix this PR instead.
> 
@ErikMogensen, of course, no issue! Thanks for the quick feedback and merge of the other PR!

2020-10-07 08:30 UTC, ErikMogensen approved these changes
Thanks @Greybird !

2020-10-07 13:44 UTC, SeanFeldman approved these changes

2020-10-07 13:45 UTC, merged

2020-10-14 06:59 UTC, paolosalvatori commented
Sorry guys for coming late, I was terribly busy during this period. Thanks @SeanFeldman @ErikMogensen