Allow selection of message counts to display
paolosalvatori/ServiceBusExplorer pull request #469
Opened 2020-10-04 15:48 UTC by Greybird

The purpose of this PR is to allow configuring the message counts that the user wants to display.

It defaults to the current display (Active/DeadLetter/Transfer DeadLetter), but also allows to select Scheduled/Transfer message counts as well. Order is not modifiable but this should already bring some value to users.

> Note that this PR might conflict with #468 due to the modification of the same code zones. I will happily handle the merge once any will be merged into the repo

# Screenshots
## Configuration
![image](https://user-images.githubusercontent.com/8553578/95019871-27430080-0668-11eb-9985-f7735188bd35.png)
## Results
Sorry, all counts are at 0, but you can get the idea
![image](https://user-images.githubusercontent.com/8553578/95020135-ab49b800-0669-11eb-9975-b54097f3b77e.png)

2020-10-04 15:49 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-counts.71.build.714 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35560044) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/8903d66b94 by @)

2020-10-04 22:38 UTC, SeanFeldman requested changes

2020-10-04 22:38 UTC, SeanFeldman commented on src/Common/Helpers/Constants.cs
> +        public const string DeadLetterMessages = "DeadLetter";
```suggestion
        public const string DeadLetterMessages = "DeadLettered";
```

2020-10-04 22:38 UTC, SeanFeldman commented on src/Common/Helpers/Constants.cs
> +        public const string TransferMessages = "Transfer";
These are messages being transfered. I wonder if the name should reflect that.

```suggestion
        public const string TransferMessages = "InTransfer";
```

2020-10-04 22:38 UTC, SeanFeldman commented on src/ServiceBusExplorer.sln.DotSettings
> +	<s:Boolean x:Key="/Default/Environment/SettingsMigration/IsMigratorApplied/=JetBrains_002EReSharper_002EPsi_002ECSharp_002ECodeStyle_002ECSharpUseContinuousIndentInsideBracesMigration/@EntryIndexedV
Likely unintended change.
```suggestion
```

2020-10-05 05:04 UTC, Greybird commented on src/Common/Helpers/Constants.cs
> +        public const string TransferMessages = "Transfer";
Seems like a good idea to me.

2020-10-05 05:05 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 4.2.0-counts.72.build.715 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/35565954) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/7e06ccc7f1 by @Greybird)

2020-10-05 05:05 UTC, Greybird commented on src/ServiceBusExplorer.sln.DotSettings
> +	<s:Boolean x:Key="/Default/Environment/SettingsMigration/IsMigratorApplied/=JetBrains_002EReSharper_002EPsi_002ECSharp_002ECodeStyle_002ECSharpUseContinuousIndentInsideBracesMigration/@EntryIndexedV
Sorry, missed that at commit & PR time 😞

2020-10-05 05:27 UTC, SeanFeldman approved these changes

2020-10-05 19:06 UTC, ErikMogensen approved these changes
Very good!

2020-10-05 19:11 UTC, merged

2020-10-14 07:01 UTC, paolosalvatori commented
This is AWESOME, thanks @Greybird :)