Upgrade service bus SDK
paolosalvatori/ServiceBusExplorer pull request #494
Opened 2021-01-02 08:29 UTC by ErikMogensen

Switch from using Microsoft.Azure.ServiceBus to Azure.Messaging.ServiceBus.

2021-01-02 08:31 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeServiceBusSdk.8.build.751 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37075282) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/27da5eb688 by @ErikMogensen)

2021-01-04 03:51 UTC, SeanFeldman requested changes

2021-01-04 03:51 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +using NewSdkManagement = Azure.Messaging.ServiceBus.Administration;
As we're not mixing the two SDKs together, is this aliasing necessary?

2021-01-04 03:51 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public async Task<NewSdkManagement.QueueProperties> GetNewSdkQueueProperties(QueueDescription oldQueueDescription)
GetNewSdkQueueProperties --> GetQueueProperties

2021-01-04 03:51 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +            var managementClient = new NewSdkManagement.ServiceBusAdministrationClient(connectionString);
Should we be consistent and adopt the new SDK naming?
If yes, `managementClient` --> `administrationClient`.

2021-01-04 09:35 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeServiceBusSdk.9.build.753 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37094873) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/54136ce1f4 by @ErikMogensen)

2021-01-04 09:37 UTC, ErikMogensen commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public async Task<NewSdkManagement.QueueProperties> GetNewSdkQueueProperties(QueueDescription oldQueueDescription)
Changed

2021-01-04 09:38 UTC, ErikMogensen commented on src/Common/Helpers/ServiceBusHelper.cs
> +            var managementClient = new NewSdkManagement.ServiceBusAdministrationClient(connectionString);
Yes, that is better. Changed it.

2021-01-04 10:29 UTC, paolosalvatori commented
@ErikMogensen did you remove the Microsoft.Azure.ServiceBus everywhere, or just in some files? What about the HandleTopicControl for example?

2021-01-04 11:01 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeServiceBusSdk.12.build.756 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37096177) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/0c655bbaa6 by @ErikMogensen)

2021-01-04 11:05 UTC, ErikMogensen commented
Yes, @paolosalvatori I removed Microsoft.Azure.ServiceBus everywhere. I dreaded a situation where we would have three Service bus SDKs. Removing the oldest SDK is quite a big task though since it is heavily used and there are message format incompatibilities including the WCF support.

2021-01-04 12:22 UTC, paolosalvatori commented
Does this mean that WCF format is no more supported? Just asking. At this point, we can also implement Azure AD authentication.

2021-01-04 12:23 UTC, paolosalvatori approved these changes

2021-01-04 15:36 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-UpgradeServiceBusSdk.14.build.760 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/37100612) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9634ee8bbf by @ErikMogensen)

2021-01-04 15:40 UTC, ErikMogensen commented
@paolosalvatori,  as I understand it WCF is not supported by the latest SDK. However, it is still supported in the current version of SBE since almost all Service Bus code in it is still using the oldest SDK.

2021-01-04 15:41 UTC, ErikMogensen commented
Also @paolosalvatori , I think you'll have to approve this one again since I made some minor changes.

2021-01-05 05:27 UTC, SeanFeldman approved these changes

2021-01-05 05:27 UTC, merged

2021-01-05 08:43 UTC, paolosalvatori commented
No worries, as I said in another comment I don't think there's no one out there that still uses WCF. We can remove WCF support from SBE eventually.