Changes the main window's text/title to ASB namespace.
paolosalvatori/ServiceBusExplorer pull request #524
Opened 2021-03-17 00:20 UTC by groozin

This brings more visibility when working with mulitple ASB connections at the same time.

2021-03-17 00:21 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-alpha.19.build.803 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38259448) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/e63642e810 by @groozin)

2021-03-17 03:29 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/MainForm.cs
> +            this.Text = $"{serviceBusNamespace.Namespace}";
Is string interpolation necessary here?

2021-03-17 09:22 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-alpha.19.build.804 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38265031) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/fe719ba646 by @groozin)

2021-03-17 09:23 UTC, groozin commented on src/ServiceBusExplorer/Forms/MainForm.cs
> +            this.Text = $"{serviceBusNamespace.Namespace}";
Nope. It is leftover from the experimentation with the text to display. Fixed in the subsequent commit now.

2021-03-17 18:34 UTC, ErikMogensen requested changes
I think the title should be "<namespace> - Service Bus Explorer". That aligns with Notepad and VS Code which has the same behavior. 

Then it would be best to put the setting of the title in a new method.

2021-03-17 22:52 UTC, SeanFeldman commented
:white_check_mark: [Build ServiceBusExplorer 5.1.0-alpha.19.build.805 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/38279037) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/f85f2dadc2 by @groozin)

2021-03-17 23:17 UTC, SeanFeldman approved these changes

2021-03-18 05:58 UTC, ErikMogensen approved these changes
Great!

2021-03-18 05:59 UTC, merged

2021-03-19 10:38 UTC, paolosalvatori commented
Thanks for the PR @groozin 😄 what is the new format for the title now? Namespace - Service Bus Explorer?