adding cloud bricks Service Bus Cloud Explorer to alternative tools
paolosalvatori/ServiceBusExplorer pull request #663
Opened 2022-07-14 10:48 UTC by harouny

2022-07-14 11:30 UTC, ErikMogensen submitted a review, later dismissed

2022-07-24 06:19 UTC, SeanFeldman requested changes

2022-07-24 06:19 UTC, SeanFeldman commented on README.md
> +- **[Service Bus Cloud Explorer](https://servicebus.cloudbricks.io/)** _(paid with a free basic plan, SaaS, web based)_
The original URL doesn't provide any information but rather requires to authenticate. I suggest changing the URL to the following:

```suggestion
- **[Service Bus Cloud Explorer](https://cloudbricks.io/products/service_bus_cloud_explorer/)** _(paid with a free basic plan, SaaS, web based)_
```

2022-07-24 06:23 UTC, AhmedAtCloudBricks commented on README.md
> +- **[Service Bus Cloud Explorer](https://servicebus.cloudbricks.io/)** _(paid with a free basic plan, SaaS, web based)_
That makes sense thanks, will change the URL

2022-07-24 06:33 UTC, SeanFeldman approved these changes

2022-07-24 06:33 UTC, merged

2022-07-24 06:34 UTC, SeanFeldman commented
Already done. Thank you @harouny.