Use GitHub actions for CI/CD
paolosalvatori/ServiceBusExplorer pull request #667
Opened 2022-07-24 16:20 UTC by ErikMogensen

Fixes #598 

Replaces Appveyor and GitVersion with GitHub Actions. It is missing a check for only releasing on the master branch (which will be ugly, see https://github.community/t/how-to-create-filter-on-both-tag-and-branch/16936/2) and do the actual publishing to Chocolatey. 

I'll fix the branch check, but I intend to wait with the publishing to Chocolatey once see that this is working.

2022-07-25 07:03 UTC, paolosalvatori commented
I don't have the bandwidth to check that everything works as expected and you are more knowledgeable than me in this area, so I trust your work and approve the PR 😄 @ErikMogensen @SeanFeldman

2022-07-25 07:03 UTC, paolosalvatori approved these changes

2022-07-25 10:10 UTC, SeanFeldman commented
@ErikMogensen it's a draft because it's still a WIP PR or is it ready to be reviewed? Thanks.

2022-07-25 11:20 UTC, ErikMogensen commented
@SeanFeldman, it is ready for review. I have now put it in 'Ready for review'.

2022-07-26 07:53 UTC, SeanFeldman requested changes
A couple of items for your review. Thanks.

2022-07-26 07:53 UTC, SeanFeldman commented on .github/workflows/build-test.yml
> +        $nunitVersion='3.15.2'
You could simplify this part by installing a global .NET tool for [NUnit](https://www.nuget.org/packages/NUnit.Console) and removing the need to specify the version and MSI installation.

2022-07-26 07:53 UTC, SeanFeldman commented on .github/workflows/handle-tag.yml
> +    - name: Exit if tag commit hash don't match master commit hash
I would suggest using a shorter `name` and using the detailed text in `description`.

Example:

```yaml: 'tag-not-found'
- name: 'Exit if tag commit hash don't match master commit hash'
- description: 
```

2022-07-26 07:53 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +        echo "The cached output was not found"
```suggestion
        echo "Couldn't find build artifacts. Expected to find artifacts in cache but no items were found."
```

2022-07-26 07:53 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +      continue-on-error: true
Is this right?

2022-07-26 07:53 UTC, SeanFeldman commented on appveyor.yml
> -skip_commits:
We should keep this part in the new flow. No need to run builds if static content files are changing.

2022-07-26 07:53 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
This is packaging Choco artifact, but where's the deployment? We'll need to have that step here as well, along with the secret set in GH secrets.

2022-07-26 12:28 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +        $nunitVersion='3.15.2'
You mean using nuget install as mentioned in https://stackoverflow.com/questions/67770726/run-nunit-test-in-git-actions-for-net-framework? 

I think it is better to use a specified version of NUnit since I don't see a problem of being a couple of releases behind the latest NUnit version, but hitting a regression bug in NUnit may take a long time to troubleshoot.

2022-07-26 12:31 UTC, ErikMogensen commented on .github/workflows/handle-tag.yml
> +    - name: Exit if tag commit hash don't match master commit hash
Sure. I'll change it to "Verify tag commit matches master commit".

2022-07-26 12:40 UTC, ErikMogensen commented on .github/workflows/publish.yml
> +      continue-on-error: true
The continue-on-error is there to handle the case if the release has already been created to handle the case if you want to overwrite an existing release. It is fine by me to remove it though.

2022-07-26 13:18 UTC, ErikMogensen commented on appveyor.yml
> -skip_commits:
Unfortunately the pull_request event does not have a paths-ignore option, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request so I don't see how that can be achieved. 

Tagging will not trigger the handling-pull-request workflow. It will trigger the handle-tag workflow though, but it will fail. As mentioned, it seems like it has to be that way.

2022-07-27 07:27 UTC, SeanFeldman commented on .github/workflows/build-test.yml
> +        $nunitVersion='3.15.2'
You can lock into a specific version if you want. The main idea was not to use an MSI installer.

2022-07-27 07:29 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +      continue-on-error: true
You mean if the publish needs to be executed more than once, right? As long as Choco is idempotent should be ok.

2022-07-27 07:37 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
@ErikMogensen are you a registered user with Chocolatey? If you are, what's the public **username** you're using?

2022-07-27 07:38 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
Is [that](https://community.chocolatey.org/profiles/erikmogensen) you, @ErikMogensen?

2022-07-27 07:42 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +        $nunitVersion='3.15.2'
Great!

2022-07-27 07:43 UTC, ErikMogensen commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
Yes :)

2022-07-27 09:00 UTC, SeanFeldman commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
👍 
Invited

2022-07-27 09:41 UTC, ErikMogensen commented on .github/workflows/publish.yml
> +      continue-on-error: true
Yes, or if the release has been previously created as a draft. I'll leave it like this for now.

2022-07-27 19:47 UTC, ErikMogensen commented on .github/workflows/publish.yml
> +    - name: Pack Chocolatey
The deployment to Chocolatey is added now.

2022-07-28 06:28 UTC, SeanFeldman approved these changes

2022-07-28 06:30 UTC, SeanFeldman commented
Approved.

README.md will need to be updated to point to GitHub rather than AppVeyor.

2022-07-28 06:44 UTC, ErikMogensen commented
@SeanFeldman, is there anything we should do with Appveyor before merging this PR? Otherwise let's merge it. I'll create a separate PR for the Readme.md.

2022-07-28 07:02 UTC, SeanFeldman commented
AppVeyor project was deleted and won't interfere with GH Actions. Good to proceed 👍

2022-07-28 07:12 UTC, merged