Event Grid Explorer - Adding Support for Event Grid V2
paolosalvatori/ServiceBusExplorer pull request #737
Opened 2023-08-16 23:51 UTC by t-wangamy

For my Summer 2023 internship project under the Azure Messaging Event Grid team, I developed the Event Grid Explorer. This is a tool integrated in Service Bus Explorer for viewing and managing Event Grid V2 entities, including namespaces, topics and subscriptions, as well as provide create/delete operations for topics and subscriptions, publish/receive operations for events, and acknowledge/release/reject operations for events.

Currently, the Event Grid Explorer features the functionality that is available for the preview version of Event Grid V2.
This additional support for Event Grid V2 enables users to test event delivery with ease, contributing to the adoption of the new service.

The modifications include creating new Controls and Forms under ServiceBusExplorer as well as adding an EventGridExplorerLibrary containing the Event Grid V2 SDK functions used

2023-08-17 04:41 UTC, SeanFeldman requested changes
Excellent job, @t-wangamy.
I left a few comments, change requests, and questions.

2023-08-17 04:41 UTC, SeanFeldman commented on EventGridExplorer_README.md
> +When receiving events through a subscription, the user can receive the maximum number of events (100) or a top number of events.
Is it "up to 100 messages from the top of the subscription"?

2023-08-17 04:41 UTC, SeanFeldman commented on EventGridExplorer_README.md
> +## Acknowledge/Release/Reject
```suggestion
## Event settlement
```

2023-08-17 04:41 UTC, SeanFeldman commented on EventGridExplorer_README.md
> +On the received events listed in the table, the user can multi-select events to perform the acknowledge/release/reject operations.
```suggestion
The user can multi-select the received events in the table to acknowledge, release, or reject events.
```

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorer.csproj.nuget.dgspec.json
> +{
This shouldn't be comitted

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorer.csproj.nuget.g.props
> +﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
It shouldn't be committed.

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorer.csproj.nuget.g.targets
> +﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
Remove?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorerLibrary.csproj.nuget.dgspec.json
> +{
Remove?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorerLibrary.csproj.nuget.g.props
> +﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
Remove?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/EventGridExplorerLibrary.csproj.nuget.g.targets
> +﻿<?xml version="1.0" encoding="utf-8" standalone="no"?>
Remove?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/.pkgrefgen/project.assets.json
> +{
Remove?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
> +		<PackageReference Include="Azure.Messaging.EventGrid" VersionOverride="4.17.0-beta.1" Version="4.17.0-beta.1" />
Are overrides necessary?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
> +		<UserSecretsId>5e9a3a5e-9d3e-4d94-9e4c-f9d6944d5d5c</UserSecretsId>
Is this project using settings that are in secrets? What are those settings?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +        private const string TenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47";
Hardcoded tenant ID?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            await dataPlaneClients[topicName].PublishCloudEventAsync(topicName, cloudEvent);
Is the expectation for events always to be in CloudEvent format? If yes, it should be called out in the readme.md

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/EventGridManagementClient.cs
> +            BaseUri = new System.Uri("https://10.135.30.79:553");
Could you provide a comment to elaborate what the URI is?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/EventGridManagementClient.cs
> +            LongRunningOperationRetryTimeout = 30;
I wonder if those should be coming from the settings. Thoughts?

2023-08-17 04:41 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Models/DeliveryConfiguration.cs
> +// <auto-generated>
All the generated types - should it be documented how to re-generate these types/classes?

2023-08-18 04:32 UTC, t-wangamy commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +        private const string TenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47";
This tenant ID is for the public cloud and other clouds (Fairfax and Mooncake) also have hardcoded tenant IDs, so I updated the Event Grid connect form for the user to select a cloud tenant and use the associated tenant ID

2023-08-18 04:33 UTC, t-wangamy commented on src/EventGridExplorerLibrary/Management/EventGridManagementClient.cs
> +            LongRunningOperationRetryTimeout = 30;
Updated the EventGridManagementClient to initialize these values based on what the user enters in the Event Grid connect form

2023-08-18 05:52 UTC, SeanFeldman requested changes
Almost there. A few comments where missed out.

2023-08-18 05:52 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            await dataPlaneClients[topicName].PublishCloudEventAsync(topicName, cloudEvent);
@t-wangamy, could you please address this one?
It looks like the only format that's supported is event cloud.

2023-08-18 05:52 UTC, SeanFeldman commented on EventGridExplorer_README.md
> +## Acknowledge/Release/Reject
@t-wangamy, are these operations not settlement?

2023-08-18 05:52 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +        private const string TenantId = "72f988bf-86f1-41af-91ab-2d7cd011db47";
Perfect. Thank you.

2023-08-18 05:52 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Models/DeliveryConfiguration.cs
> +// <auto-generated>
@t-wangamy, ☝️

2023-08-18 16:15 UTC, t-wangamy commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            await dataPlaneClients[topicName].PublishCloudEventAsync(topicName, cloudEvent);
I made this change but it was undone for some reason after I pushed the new changes, I'll update it again

2023-08-18 16:16 UTC, t-wangamy commented on EventGridExplorer_README.md
> +## Acknowledge/Release/Reject
Made this change but somehow it was undone, I'll update it

2023-08-18 19:53 UTC, t-wangamy commented on src/EventGridExplorerLibrary/Management/Models/DeliveryConfiguration.cs
> +// <auto-generated>
Still waiting on my team's response for this, but do you think it would be sufficient to write a note in the README that the Event Grid Library models are generated by Microsoft (R) AutoRest Code Generator?

2023-08-18 23:33 UTC, t-wangamy commented
@SeanFeldman Today is actually the last day of my internship so I pushed the last changes for the Event Grid Explorer README. Thank you for reviewing my work and for your helpful feedback! I think from here my team will help with making any additional changes

2023-08-19 00:59 UTC, SeanFeldman commented
> @SeanFeldman Today is actually the last day of my internship so I pushed the last changes for the Event Grid Explorer README. Thank you for reviewing my work and for your helpful feedback! I think from here my team will help with making any additional changes

@t-wangamy, thank you so much for the contribution. I'll work on bringing it to the merge point. Please let me know who can continue from your team. Maybe tag them here.

Thank you and good luck!

2023-08-22 21:17 UTC, hillaryc commented
> > @SeanFeldman Today is actually the last day of my internship so I pushed the last changes for the Event Grid Explorer README. Thank you for reviewing my work and for your helpful feedback! I think from here my team will help with making any additional changes
> 
> @t-wangamy, thank you so much for the contribution. I'll work on bringing it to the merge point. Please let me know who can continue from your team. Maybe tag them here.
> 
> Thank you and good luck!

Hi @SeanFeldman, I will continue.

2023-09-01 14:41 UTC, SeanFeldman commented
@hillaryc, great!

would you be able to review the [two remaining questions](https://github.com/paolosalvatori/ServiceBusExplorer/pull/737#pullrequestreview-1583884040)? Thank you.

2023-09-07 02:58 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/EventGridManagementClient.cs
> +            BaseUri = new System.Uri("https://10.135.30.79:553");
@hillaryc, would you be able to answer this one?

2023-09-07 02:59 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Models/DeliveryConfiguration.cs
> +// <auto-generated>
@hillaryc, would you be able to answer this one?

2023-09-07 03:06 UTC, SeanFeldman reviewed
A few clarifications, @hillaryc

2023-09-07 03:06 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +        private const int Timeout = 5000;
@hillaryc, would it be expected to change the timeout by the users of the tool?
We don't have to change it now, we just want to understand. Thank you.

2023-09-07 03:06 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            await dataPlaneClients[topicName].PublishCloudEventAsync(topicName, cloudEvent);
@hillaryc, do you happen to know if `CloudEvent` is the only option or not?

2023-09-07 03:06 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +                Task<Response<ReceiveResult>> receiveTask = dataPlaneClients[topicName].ReceiveCloudEventsAsync(topicName, subscriptionName, maxEvents: maxEventNum);
@hillaryc, same question here.

2023-09-07 03:06 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +                    case "Acknowledge":
Is there a public doco for the actions?

2023-09-22 15:26 UTC, SeanFeldman commented
@hillaryc, would you be able to assist with the questions/clarifications? I'd like to wrap up the PR. Thank you for your help.

2023-09-22 19:27 UTC, hillaryc commented
Yes, I will work on this today. 😊
Best Regards,
Hillary

From: Sean Feldman ***@***.***>
Sent: Friday, September 22, 2023 8:26 AM
To: paolosalvatori/ServiceBusExplorer ***@***.***>
Cc: Hillary Caituiro Monge ***@***.***>; Mention ***@***.***>
Subject: Re: [paolosalvatori/ServiceBusExplorer] Event Grid Explorer - Adding Support for Event Grid V2 (PR #737)


@hillaryc<https://github.com/hillaryc>, would you be able to assist with the questions/clarifications? I'd like to wrap up the PR. Thank you for your help.

—
Reply to this email directly, view it on GitHub<https://github.com/paolosalvatori/ServiceBusExplorer/pull/737#issuecomment-1731611113>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AT3VM5QA4PB43M5AUAFPOP3X3WUZZANCNFSM6AAAAAA3THR3GQ>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2023-09-27 16:39 UTC, SeanFeldman commented
> Yes, I will work on this today. 😊

Thank you, @hillaryc.

2023-09-28 22:14 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            await dataPlaneClients[topicName].PublishCloudEventAsync(topicName, cloudEvent);
Yes, CloudEvent is the only option.

2023-09-28 22:26 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +                Task<Response<ReceiveResult>> receiveTask = dataPlaneClients[topicName].ReceiveCloudEventsAsync(topicName, subscriptionName, maxEvents: maxEventNum);
yes, cloud event is the only option

2023-09-28 22:42 UTC, hillaryc commented on src/EventGridExplorerLibrary/Management/EventGridManagementClient.cs
> +            BaseUri = new System.Uri("https://10.135.30.79:553");
Looks like this hardcoded URI has been removed from the last iteration.   That was being using during development.

2023-09-28 22:46 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +        private const int Timeout = 5000;
Looks like this Timeout has been removed in the last iteration and added to the connect form as a parameter.

2023-09-28 22:48 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +                    case "Acknowledge":
Yes, these are at: https://learn.microsoft.com/en-us/rest/api/eventgrid/dataplanepreview-version2023-06-01/receive-cloud-events/receive-cloud-events?tabs=HTTP

2023-09-28 22:49 UTC, hillaryc commented
I believe I replied all questions  :)   Let me know if anything

2023-10-09 15:18 UTC, hillaryc commented
Hi @SeanFeldman, let me know if there is anything pending to be done to merge this.

2023-10-10 04:24 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Models/DeliveryConfiguration.cs
> +// <auto-generated>
@hillaryc, it would be good to know how to regenerate these files in the future. Feel free to raise a separate issue to get a placeholder. Thank you.

2023-10-10 05:01 UTC, SeanFeldman commented
@hillaryc, code-wise, except for the lack of information on how to regenerate the auto-generated code, the rest is OK. These are the issues I've run into while manually testing the branch.

1. **API version** - there's no default and no dynamic selector to allow users to choose from something. I suggest putting a default. I've used `2023-06-01-preview`.
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/1309622/b657fade-44eb-4408-87e3-23196f6ceb6d)

2. **Multi-tenant users** - I have multiple tenants and subscriptions. There's no way to indicate what tenant should be used. I've failed to log into the subscription I've provided the information for in the login/credentials screen.

Error message (redacted)
```
Exception: The access token is from the wrong issuer 'https://sts.windows.net/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx/'. It must match the tenant 'https://sts.windows.net/yyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/yyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyy' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
```

The last issue is a blocker. Since there's no simple connection string and the only way to connect is to provide resource group, subscription ID, and the EG namespace (in addition to the API version), it's unclear how to troubleshoot the connectivity when an error such as this is encountered.

2023-10-10 05:05 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
@hillaryc @paolosalvatori, I might be wrong but shouldn't this be removed in favour of https://github.com/paolosalvatori/ServiceBusExplorer/blob/main/LICENSE.txt?

2023-10-10 15:59 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
You are right, I will remove it.

2023-10-26 06:31 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
Thank you, @hillaryc.

Also, my comment [here](https://github.com/paolosalvatori/ServiceBusExplorer/pull/737#issuecomment-1754380171).

2023-10-31 19:47 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
@hillaryc, ping 🙂

2023-10-31 23:03 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
Hi @SeanFeldman, looks like I do not have write access.  Could you please give me access or remove the copyright notice from the file?

2023-10-31 23:19 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
@hillaryc, I'm less worried about the header (I'll remove it) and more about the fact that I couldn't run it. See my comment [here](https://github.com/paolosalvatori/ServiceBusExplorer/pull/737#issuecomment-1754380171)

2023-11-02 19:19 UTC, hillaryc commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
Have you tried entering your tenant id in the Custom Tenant Id section?  Unfortunately, in EG we do not have connection strings.   I agree that we should have the API version prepopulated to help customers.

2023-11-03 20:37 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +﻿// Copyright (c) Microsoft Corporation.  All rights reserved.
> Have you tried entering your tenant id in the Custom Tenant Id section?

Yes. I also tried different subscriptions.

> I agree that we should have the API version prepopulated to help customers.

I'll add that

2023-11-05 21:25 UTC, SeanFeldman commented
@hillaryc, something is off about this PR.

1. It took several subscriptions to connect to a namespace.
2. When creating subscriptions, there's no way to provide filters. Those cannot be updated later either and require Azure Portal.
3. I was unsuccessful in following the documentation to publish and receive an event.

I'll merge the PR, but further work is required, I suspect.

cc @paolosalvatori @ErikMogensen

2023-11-05 21:27 UTC, SeanFeldman approved these changes
@paolosalvatori or @ErikMogensen, I'm not blocking the PR, but I couldn't verify that it's working end-to-end. Please take a look at my comment on the PR.

2023-11-07 06:42 UTC, ErikMogensen commented
I was also unable to connect to a Event Grid namespace using a Microsoft account. It worked using a work account. 

I agree about it would be useful to know how the autogenerated files were created since the service API will likely change in the future.

2023-11-09 17:38 UTC, SeanFeldman commented
**Status update**

The PR is returning to a draft mode to address usability and maintainability.
In addition to that, there will be an effort to transition off auto-generated code to the Azure SDK and the ability to add/alter subscription filters, which is essential for working with EG v2.

2024-05-22 06:46 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +            return eventGridNamespace;
```suggestion
            return await eventGridControlPlaneClient.GetNamespaceResource(resourceGroupName, namespaceName).GetAsync();
```

2024-05-22 06:46 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/EventGridLibrary.cs
> +                return result;
Since the result is returned, can we return the moment the result is available and not do chained if/else statements?

2024-05-27 04:50 UTC, SeanFeldman requested changes

2024-05-27 04:50 UTC, SeanFeldman commented on src/Common/Helpers/EventGridException.cs
> +    public class EventGridException : Exception
Question - what does this custom exception type bring that is not handled by `Exception`?

2024-05-27 04:50 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/EventGridFilterValues.cs
> +    /// Implementation of the EventGridFilterValues class
Could it be something more explanatory?

2024-05-27 04:50 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/EventGridFilterValues.cs
> +        }
Let's keep spaces between methods.

2024-05-27 04:50 UTC, SeanFeldman commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +    <PackageReference Include="WindowsAzure.ServiceBus" Version="7.0.1" />
Two versions of the same package?

2024-05-27 04:50 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Clients/EventGridControlPlaneClient.cs
> +            EventGridFilterValues eventGridFilterValues = new EventGridFilterValues();
After looking at what is done here, in the loop, and what this `EventGridFilterValues` class is, I believe this is fragmented logic between two locations. Here's what I propose.

1. `EventGridFilterValues` become an `EventGridFilterFactory`
2. Do not construct filters in the loop, it should be the factory's responsibility. You already have a method per filter type.
3. Invoke the factory in the following manner: `var filter = eventGridFilterFactory.CreateBooleanFilter(value);`

Further simplification would be to pass into the factory the `operatorType`, the `value`, and they `key` and return a base filter type that would be added to the collection `filtersConfiguration.Filters`. I'm not familiar with the EventGrid v2 SDK but sounds like that should be possible to avoid this repetition of logic and multiple `if` statements.

2024-05-27 20:15 UTC, ErikMogensen requested changes
Please make sure it builds without errors and warnings.

2024-05-27 20:15 UTC, ErikMogensen commented on src/Common/Common.csproj
> +    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
You should be able to remove those two references.

2024-05-27 20:15 UTC, ErikMogensen commented on src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
> +		<PackageReference Include="Azure.Identity" Version="1.9.0" />
There is a warning about security for this version of Azure.Identity...

2024-05-27 20:15 UTC, ErikMogensen commented on src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
> +		<PackageReference Include="Azure.Messaging.EventGrid" Version="4.17.0-beta.1" />
I see that this is an old version of the EventGrid package. I assume you want to use the latest.

2024-05-29 19:22 UTC, SeanFeldman commented on src/Common/Helpers/EventGridException.cs
> +    public class EventGridException : Exception
I must have missed that use. Could you point to where it's used? Thanks.

2024-05-29 19:27 UTC, SeanFeldman commented on src/Common/Helpers/EventGridException.cs
> +    public class EventGridException : Exception
Found it [here](https://github.com/paolosalvatori/ServiceBusExplorer/pull/737/files#diff-124052316a7afd12f79e59f2ff5512bfdf5954d536f788af9d266184c5ffc365R224). That use is on the form. When an exception is thrown, the form logs it and swallows the exception. But with EventGrid, you're going to throw? Could you help me understand why it would need to be re-thrown?

2024-05-29 19:28 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/CreateEventGridSubscriptionForm.cs
> +                throw ex;
See my other [comment](https://github.com/paolosalvatori/ServiceBusExplorer/pull/737/files#r1619376219).

2024-05-29 20:13 UTC, harrieoriowo commented on src/Common/Helpers/EventGridException.cs
> +    public class EventGridException : Exception
I might be missing something and would love to meet today to resolve it if possible.

2024-05-29 20:19 UTC, ErikMogensen commented on src/ServiceBusExplorer/Forms/CreateEventGridSubscriptionForm.cs
> +                throw ex;
Don't do: 
`throw ex;`
instead do:
`throw`

Otherwise the stack trace is lost.

2024-05-29 20:45 UTC, harrieoriowo commented on src/EventGridExplorerLibrary/EventGridExplorerLibrary.csproj
> +		<PackageReference Include="Azure.Messaging.EventGrid" Version="4.17.0-beta.1" />
It seems like the newest version has a lot of changes to some of the methods, so I might take me longer than today to refractor it all. Working on it!

2024-05-30 08:29 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/CreateEventGridSubscriptionForm.cs
> +                throw ex;
He can't do that, @ErikMogensen. Not the way you suggested. The exception was not caught in this method with a try/catch. It was passed it.

But the problem is not rethrowing. Why do we even throw if the `HandleException()` method is supposed to log and swallow exceptions? What's so special about EventGrid that it requires to throw here? Isn't it going to crash the UI?

@harrieoriowo, could you answer these questions? Thank you.

2024-05-30 08:39 UTC, SeanFeldman requested changes

2024-05-30 08:39 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Clients/EventGridControlPlaneClient.cs
> +                if (operatorType.Equals("Is not null")) { eventGridFilterFactory.AddFilterForIsNotNull(key); };
Good, @harrieoriowo!

The next step would be to take all of these `if`s and push into the factory. The `EventGridControlPlaneClient` should be dealing with the logic of creating the right filter based on the the string value of the `operatorType`. That's literally what a factory is for 🙂

2024-05-30 08:39 UTC, SeanFeldman commented on src/EventGridExplorerLibrary/Management/Clients/EventGridControlPlaneClient.cs
> +                if (operatorType.Equals("Boolean equals")) { eventGridFilterFactory.AddFilterForBoolEquals(key, value); };
You might want extract these constants as some of those appear in more than one spot.

2024-05-30 21:49 UTC, SeanFeldman reviewed
Much better, @harrieoriowo  🙂 
Let me know when you're done-done (out of draft) and I'll give it a final review.

2024-05-30 22:04 UTC, harrieoriowo commented
I believe I am done-done. I have opened it for final review!

2024-06-08 18:38 UTC, SeanFeldman requested changes
Nullable reference type warnings - either don't use it or apply on the file level. Please don't turn it off at the line-by-line level.

2024-06-08 18:38 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/CreateEventGridTopicForm.cs
> +#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
Defining a parameter as nullable to turn off the warning about the nullable usage doesn't seem right. If you want to use `Exception?`, which I support 100%, you must enable nullable reference types on the project or file level. The project level might be too much at this point, but at the file level, you could.

2024-06-08 18:38 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/PublishEventForm.cs
> +#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
The nullable remark from above

2024-06-08 18:38 UTC, SeanFeldman commented on src/ServiceBusExplorer/Forms/ReceiveEventForm.cs
> +#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
The nullable remark from above

2024-06-08 18:39 UTC, SeanFeldman commented
@harrieoriowo, overall, looks good. Once you're done with the last review comments, I'm 👍 to merge. Thank you.

2024-06-10 20:15 UTC, harrieoriowo commented on src/ServiceBusExplorer/Forms/CreateEventGridTopicForm.cs
> +#pragma warning disable CS8632 // The annotation for nullable reference types should only be used in code within a '#nullable' annotations context.
I understand your support to use `Exception?`, but it dawned on me that the method is a private method that is called in a `catch` block, where it is certain the error thrown, `ex`, will not be null. So, I removed the `?` by the parameter name. Also, the whole project does not enable nullable reference types, so enabling it on multiple files feels weird. Let me know what you think?

2024-06-10 20:44 UTC, SeanFeldman approved these changes

2024-06-10 22:24 UTC, merged