Add the ability to cancel scheduled messages
paolosalvatori/ServiceBusExplorer pull request #746
Opened 2023-10-22 20:21 UTC by ErikMogensen

This PR adds the ability to cancel scheduled messages on queues. The Service bus API does not support browsing scheduled messages on subscriptions. 

A new context menu item "Cancel Scheduled Message" has been added as shown below:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/341455c3-a6b4-42e0-8850-06b485627624)

If multiple messages are selected it says "Cancel Scheduled Messages" instead:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/7db04b45-5f2f-4b4f-8d76-8dc477dc36a1)

If the _Disable Accidental Deletion Prevention_ is disabled, a message box will ask for confirmation. 

The rows in the grid will not update, nor will the message count for the queue in the tree view. That is something that may be added later.

2023-10-23 02:54 UTC, SeanFeldman requested changes

2023-10-23 02:54 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +            return true;
It's not critical, but could be expressed as a linq statement.

2023-10-23 02:54 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (messagesDataGridView.SelectedRows.Count <= 0)
Doesn't need to be in the try/catch, right?

2023-10-23 02:54 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                        writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
Suggestion:
Aggregate all tasks and use `Task.WhenAll`. Then, log all sequence numbers if that's necessary.

2023-10-23 02:54 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +            }
```suggestion
             cancelScheduledMessageToolStripMenuItem.Text = multipleSelectedRows
              ? "Cancel Scheduled Messages"
              : "Cancel Scheduled Message";
```

2023-10-23 02:54 UTC, SeanFeldman commented
Looking good, @ErikMogensen. A few questions/suggestions.

2023-10-23 05:46 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    if (null != sequenceNumber)
Otherwise the compiler complains about a null value.

2023-10-23 05:47 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +        bool AreAllSelectedMessageScheduled(DataGridViewSelectedRowCollection selectedRows)
Fixed

2023-10-23 06:06 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +            return true;
Changed

2023-10-23 07:23 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                        writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
I'd say that the logging is necessary since it is the only indication you get that if it succeeds. 

If one task fails it will be good to know which messages were cancelled. It is of course possible to create a separate task for doing both operations, but I think that's overkill.

2023-10-23 07:26 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (messagesDataGridView.SelectedRows.Count <= 0)
I assumed it needed that since it is called from the UI thread, but apparently it is handled by the registered exception handler 😄

2023-10-26 06:29 UTC, SeanFeldman approved these changes
I'm not going to block, but I'd like you to double-check a couple of comments/suggestions. Thanks, Erik!

2023-10-26 06:29 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (null != sequenceNumber)
Something doesn't add up here.
If we have a list of messages, those must have sequence numbers. There's no message w/o a sequence number. I'd double-check that as the null check here feels off.

2023-10-26 06:29 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    await queueClient.CancelScheduledMessageAsync((long)sequenceNumber);
When we get the sequence numbers into a list, that's when we can cast to `long`.

2023-10-26 06:29 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
We could have a helper method that would take a queue client, sequence number and would cancel the message and log the sequence number. That method could be a task call for each sequence number. That way, you could use `Task.WhenAll`. For scenarios when someone is cancelling a large amount of messages, it will be more helpful than executing sequentially.

2023-10-29 09:30 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
Yes, that's what I wrote in my comment 😄 

I implemented that as 

`await Task.WhenAll(sequenceNumbersToCancel.Select(s => CancelScheduledMessageWithLogAsync(queueClient, s)));
`

and a new method:

```
async Task CancelScheduledMessageWithLogAsync(QueueClient queueClient, long sequenceNumber)
{
    await queueClient.CancelScheduledMessageAsync(sequenceNumber);
    writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
}
```

However, that didn't work when cancelling 10 000 messages. The UI froze and it started throwing exceptions. Looking at the implementation for the logging I am pretty sure it is not thread safe. 

So I reverted the code and brought it back to the original.

2023-10-29 09:59 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (null != sequenceNumber)
I agree. When I removed the null conditional operator in 
`var sequenceNumbersToCancel = messages.Select(s => s?.SequenceNumber).ToList();`
it stopped complaining about null. However, if an item in the list is null it will pass null to the method. I don't see how that could happen though so now it is without that operator.

2023-10-31 19:35 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (null != sequenceNumber)
I would suggest filtering out any message that is coming from the grid as `null` and getting rid of the conditional execution.

```
 var sequenceNumbersToCancel = messages.Where(x => x is not null).Select(x => x.SequenceNumber).ToList();
```

2023-10-31 19:40 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    await queueClient.CancelScheduledMessageAsync((long)sequenceNumber);
See comment [here](https://github.com/paolosalvatori/ServiceBusExplorer/pull/746/files/e16d80d332c1839011f664e57a08fe88546357eb#r1378086040).

2023-10-31 19:46 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
`WriteToLog` is a delegate passed in from the `MainForm` when the control is constructed ([reference](https://github.com/paolosalvatori/ServiceBusExplorer/blob/3cfbe19e4a1c5e083496b2af905ff33df02f2656/src/ServiceBusExplorer/Forms/MainForm.cs#L4736)).
There's also a [`AsyncWriteToLog`](https://github.com/paolosalvatori/ServiceBusExplorer/blob/3cfbe19e4a1c5e083496b2af905ff33df02f2656/src/ServiceBusExplorer/Forms/MainForm.cs#L3200). Given the context here is asynchronous, should the asynchronous version be used?

2023-10-31 21:10 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                if (null != sequenceNumber)
I just saw your comment after implementing a change in a different way.

2023-10-31 21:11 UTC, ErikMogensen commented on src/ServiceBusExplorer/Controls/HandleQueueControl.cs
> +                    writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
I missed that one. I'll take a look at it.

2024-02-13 21:41 UTC, ErikMogensen commented
@SeanFeldman, there were quite a few changes since your review. Do you want to take another look?

When I limited it to 40 parallel tasks it is quite fast and works 😄 
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/a9ae5575-3b27-4030-8295-52c2bc349d53)

I also added a new context menu item for selecting all rows

Selected a single, normal messages:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/a6ff9686-e4c1-43b3-a3d8-f4a4e70469ad)

Selected multiple, normal messages:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/737b95c8-c143-4e3e-8a2c-7c86546dee60)

Selected a single, dead-letter messages:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/bbb6f01e-12fa-41ed-b4d4-b7337359abfd)

Selected multiple, deadletter messages:
![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/9644248/20790471-2806-4079-a710-6539939f524f)

2024-02-14 02:05 UTC, SeanFeldman commented on src/ServiceBus/Helpers/ServiceBusHelper2.cs
> +        // Remember to dispose of the client after use, using client.DisposeAsync()
Is this for the callers?

2024-02-14 06:44 UTC, ErikMogensen commented on src/ServiceBus/Helpers/ServiceBusHelper2.cs
> +        // Remember to dispose of the client after use, using client.DisposeAsync()
Yes. What do you think of changing the comment to: 
`// Callers shall dispose the client after use, using client.DisposeAsync()`

?

I was thinking of creating a public method that only did a client.DisposeAsync() to get symmetry but felt it was overkill.

2024-02-14 15:08 UTC, SeanFeldman commented on src/ServiceBus/Helpers/ServiceBusHelper2.cs
> +        // Remember to dispose of the client after use, using client.DisposeAsync()
The wording is ok.
It's hard to enforce that with an inline comment. I was thinking that maybe it should be a `<remark>` on the mehothod's XML doc (`<summary>`).

2024-02-14 21:37 UTC, ErikMogensen commented on src/ServiceBus/Helpers/ServiceBusHelper2.cs
> +        // Remember to dispose of the client after use, using client.DisposeAsync()
I just pushed an update for that comment. Are we good to go?

2024-02-14 23:04 UTC, SeanFeldman commented on src/ServiceBus/Helpers/ServiceBusHelper2.cs
> +        // Remember to dispose of the client after use, using client.DisposeAsync()
Yep. Just added a tiny suggestion [here](https://github.com/paolosalvatori/ServiceBusExplorer/pull/746/files/522bcd5825093667866c1daa8d45d38d4edba8eb..b8486f154c9ae7720d6e23e77cf2acac6abfd43b#r1490169974).

2024-02-14 23:24 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                        .ContinueWith((t) => semaphore.Release()));
```suggestion
                        .ContinueWith(t => semaphore.Release()));
```

2024-02-14 23:35 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                serviceBusHelper.WriteToLog($"Cancelled {sequenceNumbersToCancel.Count} scheduled message(s) in {stopwatch.ElapsedMilliseconds / 1000} seconds.");
I would go with `Elapsed` because it's a `TimeSpan` formatted automatically. If purging takes a few milliseconds, seconds, or minutes, it will always be in the same readable format `00:00:00.0000000`.

```suggestion
                Func<string> singleOrPlural = () => sequenceNumbersToCancel.Count() > 1 ? "messages": "message";
                serviceBusHelper.WriteToLog($"Cancelled {sequenceNumbersToCancel.Count} scheduled {singleOrPlural()} in {stopwatch.Elapsed}.");
```

2024-02-14 23:43 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +            writeToLog($"Cancelled scheduled message with sequence number {sequenceNumber}.");
@ErikMogensen, I don't think you want to wait here... you want to fire and hand over the task to the caller (`CancelScheduledMessages`).
```suggestion
            var task = sender.CancelScheduledMessageAsync(sequenceNumber).ContinueWith(
               (t, state) => writeToLog($"Cancelled scheduled message with sequence number {state}."),
                sequenceNumber);
            return task;
```

2024-02-15 08:11 UTC, SeanFeldman approved these changes

2024-02-16 04:45 UTC, SeanFeldman commented
Some thoughts about this PR in light of some benchmarking that was done.

It is worth mentioning that this is related to #360. We closed the issue as `won't fix` because, with any significant number of scheduled messages, this approach (PeekLock and delete) might fail or take a long time. For example, running outside of an Azure data center and cancelling 500K messages of average size can take anywhere between 1 and 1.5 hours.

I also benchmarked an alternative approach, which is more intrusive, using auto-forwarding and a temporary queue. Assuming there's a `source` queue with scheduled and active messages, auto-forwarding is set to a temporary queue `temp`. Active messages are drained to the temporary `temp` queue. At that point, the original `source` queue is deleted and recreated (a short delay is required to avoid resource creation conflict error). And the last step is to forward backed-up messages from the `temp` queue back to the newly re-created `source`, deleting the temporary `temp` queue. With a similar number of scheduled messages and 1000 active messages to emulate in-flight messages, it took under 30 seconds (manual verification).

While I still rather see ASB [supporting purging](https://github.com/Azure/azure-service-bus/issues/1) (scenario when there are no inflight messages or those don't matter) and ability to get [peek messages by status](https://github.com/Azure/azure-service-bus/issues/95), for large quantities of scheduled messages, the auto-forwarding option might be better suited. Foot for thought

2024-02-18 16:05 UTC, ErikMogensen commented
Fixed it to build and handle failed cancellations. Tested with 100.000 messages and it took a bit less than ten minutes to cancel all of them.

@SeanFeldman, interesting solution. What do you mean by:
> this approach (PeekLock and delete)

2024-02-18 16:35 UTC, SeanFeldman commented
I meant PeekLock and complete.
The alternative is too destructive and would mess up anything that relies on the resource ID. Like monitoring and alerting. That’s why it really should be a service side capability (https://github.com/Azure/azure-service-bus/issues/698).

2024-02-18 16:41 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                    Func<string> failuresSingleOrPlural = () => failures.Count > 1 ? "messages" : "message";
It’s identical to `successesSingleOrPlural`. Merge the two?

2024-02-18 16:43 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                    tasks.Add(CancelScheduledMessageWithLog(sender, sequenceNumber, serviceBusHelper.WriteToLog, successes, failures)
What do you think of combining the success and the failure counters into a `OperationStatus`?

2024-02-18 19:38 UTC, ErikMogensen commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                    tasks.Add(CancelScheduledMessageWithLog(sender, sequenceNumber, serviceBusHelper.WriteToLog, successes, failures)
You mean create a class like this?

```
class OperationStatus
{
    public int Successes; 
    public int Failures; 
}
```

2024-02-18 19:42 UTC, SeanFeldman commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                    tasks.Add(CancelScheduledMessageWithLog(sender, sequenceNumber, serviceBusHelper.WriteToLog, successes, failures)
Yeah, something like that. Those two counters represent a result of a single operation and are coupled.

2024-02-18 21:02 UTC, ErikMogensen commented on src/ServiceBus/Helpers/CancelScheduledMessagesHelper.cs
> +                    tasks.Add(CancelScheduledMessageWithLog(sender, sequenceNumber, serviceBusHelper.WriteToLog, successes, failures)
That's right. Pushed a change to use such a class.

2024-02-18 21:18 UTC, ErikMogensen commented
> I meant PeekLock and complete.
Do you mean the solution I did and you just reviewed? It is using Peek to find out status and then CancelScheduledMessages on the scheduled messages.

2024-02-18 21:22 UTC, SeanFeldman commented
> Do you mean the solution I created and you just reviewed? It is using Peek to find out status and then CancelScheduledMessages on the scheduled messages.

Yes. There's no other option today. Except the one I mentioned but it's not "safe".

2024-02-19 19:31 UTC, ErikMogensen commented
@SeanFeldman, do you approve of this PR now?

2024-02-19 19:45 UTC, SeanFeldman commented
> @SeanFeldman, do you approve of this PR now?

![image](https://github.com/paolosalvatori/ServiceBusExplorer/assets/1309622/fa845086-1b80-4d0f-bb4e-75016dfc8da8)

👍

2024-02-19 19:57 UTC, merged