Warnings as errors and upgrade setupMsBuild
paolosalvatori/ServiceBusExplorer pull request #779
Opened 2024-06-03 05:56 UTC by ErikMogensen

Try /WarnAsError to block builds with warnings. 
Upgrade SetupMSBuild to Node.js 20 version

2024-06-03 22:45 UTC, SeanFeldman requested changes

2024-06-03 22:45 UTC, SeanFeldman commented on .github/workflows/build-test.yml
> +        msbuild /WarnAsError /m /property:Configuration=${{env.BUILD_CONFIGURATION}},FileVersion=${{env.NUMBER_VERSION}},InformationalVersion=${{inputs.release-version}} ${{env.SOLUTION_FILE_PATH}}
It would be better to do that in the solution/projects. That way, it's consistent locally and on the build server. Otherwise, contributors will not see those errors until push their changes up.

2024-10-28 11:14 UTC, asos-gurpreetsingh commented
I think this would not be needed anymore since the build is now using dotnet build. unless those warning are still a problem in which case those warning need to be tackled.

2025-02-01 13:10 UTC, ErikMogensen commented
We do want to block the build when there are errors. Created PR #825 for this.

2025-02-01 13:10 UTC, closed without merging