#758
paolosalvatori/ServiceBusExplorer pull request #780
Opened 2024-06-03 20:25 UTC by kjakee

Increased the timeout so that it can process a large volume of message from dead letter queue in a batch. Also added a log information so that it logs the sequence number of the message moved from dead letter queue. I hope it fix the issue #758.

2024-06-03 22:42 UTC, SeanFeldman requested changes

2024-06-03 22:42 UTC, SeanFeldman commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                            WriteToLog($"Moving a message with sequence number {message.SequenceNumber}.");
Would it make sense to indicate moving from where to where? I.e. 
> Moving message with sequence number 1234567890 from queue.dead-letter to queue

2024-06-03 22:42 UTC, SeanFeldman commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
Please elaborate.
This `maTimeInSeconds` is driven by `GetMaxOperationTimeInSeconds()` which [returns](https://github.com/paolosalvatori/ServiceBusExplorer/blob/18c52d79731775e8e8a845ee6cb75b541d25e0c3/src/Common/Helpers/DeadLetterMessageHandler.cs#L347) `MaxLockDuration` of the entity and that cannot be changed (not today)

2024-06-18 16:46 UTC, kjakee commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
Per my understand stopwatch.ElapsedMillisecondsis here is the time of the max lock duration - for a large batch of messages i.e. 2000 messages, the processing time exceeds it if we do not increase it sufficiently. For that reason, I have multiplied maxTimeInSeconds to a large number instead of 1000. The alternate way of doing this might be increasing maxTimeInSeconds instead of increasing 1000 to 100000 here.

2024-06-18 16:46 UTC, kjakee commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                            WriteToLog($"Moving a message with sequence number {message.SequenceNumber}.");
yes, that makes better sense.

2024-06-18 17:43 UTC, ErikMogensen commented on .github/workflows/dotnet-desktop.yml
Is this file supposed to be part of the PR?

2024-06-18 17:52 UTC, ErikMogensen commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
If you increase the duration longer than the maximum lock duration, then the messages will most likely not be deleted, which is undesirable.

2024-06-18 17:56 UTC, kjakee commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
Based on my most recent testing - I tried several times with almost 2000 messages in batch. Every time the messages got cleared up as expected.

2024-06-18 18:46 UTC, ErikMogensen commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
How long did it take and what is the Max Lock Duration for the queue/subscription?

2024-06-18 18:53 UTC, kjakee commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
For 2000 messages it took almost 2 and half an hour to reprocess and cleared up the dead letter queue. The max lock duration for the subscription was 1 minute.

2024-06-18 19:01 UTC, ErikMogensen commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
Hmm, interesting. That's an extremely long time for handling 2,000 messages though. Are you aware of any reason for this?

2024-06-18 19:08 UTC, kjakee commented on src/Common/Helpers/DeadLetterMessageHandler.cs
> +                    if (stopwatch.ElapsedMilliseconds >= maxTimeInSeconds * 100000)// changed from 1000 to 100000
Those 2000 message were sent to reprocess in a subscription which triggers a service bus trigger azure function. I suspect a potential reason was the batch mode was not enabled in that azure function.

2025-02-25 00:01 UTC, closed without merging