Update Nunit packages and fix breaking changes
paolosalvatori/ServiceBusExplorer pull request #801
Opened 2024-08-08 14:28 UTC by asos-gurpreetsingh

2024-08-08 14:35 UTC, SeanFeldman requested changes
Thank you, @asos-gurpreetsingh. The unit tests in this project are... insufficient to say the least.
Looking at the changes to NUnit, I'm inclined to decline this. Here's why

This new NUnit API is attempting to mimic [Fluent Assertions](https://fluentassertions.com) but looks off. Take the following example:

```
Assert.That(false, Is.EqualTo(nonExistingValueAsFalse));
``

Every assertion has to have `Assert.That()` as a container method. With Fluent Assertion, the same would be more readable.

```
nonExistingValueAsFalse.Should().BeFalse();
```

The benefits IMO are
1. More fluid
2. No "container method"
3. Reads better for humans

I can support Fluent Assertions if you'd like. However, replacing an existing clunky NUnit API with another variant is not worth it.

2024-08-08 14:40 UTC, asos-gurpreetsingh commented
Thanks @SeanFeldman , are we saying that if we update the Nunit package then we want to use fluent assertions otherwise we will never update Nunit package ?

2024-08-08 14:52 UTC, SeanFeldman commented
Is the new API mandatory for the latest version of NUnit?

2024-08-08 14:54 UTC, asos-gurpreetsingh commented
The old methods were not available when I updated

2024-08-08 15:49 UTC, SeanFeldman commented
Thanks, @asos-gurpreetsingh.
If you're already at it, we might as well swap NUnit with XUnit. It's a more commonly used library this days, including MSFT projects.

2024-08-11 19:59 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +    runs-on: windows-latest
I think it is better to fix the OS version. That way you are in control of it. That trumps the disadvantage of having to update it every third year or so.

2024-08-11 20:01 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
I doubt that dotnet build sets File version and Informational version on .NET Framework assemblies. Have you checked this?

2024-08-11 20:03 UTC, sean-feldman-sh commented on .github/workflows/build-test.yml
> +    runs-on: windows-latest
Is there anything specific from Windows 2022 OS we require? I'm actually in favor of running with the latest. If it doesn't cause anything to fail during the build, were covered. If the latest will cause something to break, we'll investigate and fix it. So +1 to go with the latest for the build pipeline.

2024-08-11 20:08 UTC, ErikMogensen reviewed
I like the switch to xUnit and the new assertions.

2024-08-11 20:08 UTC, ErikMogensen commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
Why was this line added?

2024-08-11 20:08 UTC, ErikMogensen commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
I also wonder what this line does?

2024-08-11 20:08 UTC, SeanFeldman requested changes
A couple of minor things. The xUnit changes look good.

2024-08-11 20:08 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/TrackBar.cs
> -				if (minimum > value)
This is not part of xUnit migration. Let's make it a separate PR.

2024-08-11 20:08 UTC, SeanFeldman commented on src/ServiceBusExplorer/Controls/TrackBar.cs
> -				if (maximum < value)
This is not part of xUnit migration. Let's make it a separate PR.

2024-08-11 20:08 UTC, SeanFeldman commented on src/ServiceBusExplorer/UIHelpers/CustomPropertyDescriptor.cs
> +            get => attributes.OfType<DefaultValueAttribute>().FirstOrDefault()?.Value;
This is not part of xUnit migration. Let's make it a separate PR.

2024-08-11 20:10 UTC, SeanFeldman commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
> Provides classes which read and write resources in a format that supports non-primitive objects.

I don't see it used anywhere though.

2024-08-11 20:11 UTC, SeanFeldman commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
If this is not part of xUnit migration then let's make it a separate PR.

2024-08-11 20:21 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +    runs-on: windows-latest
As far as I know there isn't anything in the build that requires it to run on Windows 2022, but investigating an issue which is due to running on another OS version gets more complicated since you'll start by checking the updated source code.

2024-08-12 09:57 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
I can see the assembly version set when I build it on my machine with same command

2024-08-12 12:20 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +    runs-on: windows-latest
reverted to windows-2022

2024-08-12 12:27 UTC, asos-gurpreetsingh commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
dotnet build command fails while complaining that it cannot find this namespace at run time
![image](https://github.com/user-attachments/assets/3f6c7b87-8e40-4dfa-bc8c-6a70b8a1885e)

2024-08-12 12:27 UTC, asos-gurpreetsingh commented on src/ServiceBusExplorer/UIHelpers/CustomPropertyDescriptor.cs
> +            get => attributes.OfType<DefaultValueAttribute>().FirstOrDefault()?.Value;
reverted

2024-08-12 13:26 UTC, SeanFeldman approved these changes

2024-08-12 13:31 UTC, SeanFeldman commented
I don't recall wherever PR build should have a version or not. @ErikMogensen do you remember?

![Screenshot_2024-08-12-07-29-57-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/5ac35287-75a2-4cb7-9eb2-d22c5c71b6b6)

2024-08-12 14:02 UTC, asos-gurpreetsingh commented
> I don't recall wherever PR build should have a version or not. @ErikMogensen do you remember?
> 
> ![Screenshot_2024-08-12-07-29-57-87_40deb401b9ffe8e1df2f1cc5ba480b12](https://private-user-images.githubusercontent.com/1309622/357065965-5ac35287-75a2-4cb7-9eb2-d22c5c71b6b6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NzE0NjEsIm5iZiI6MTcyMzQ3MTE2MSwicGF0aCI6Ii8xMzA5NjIyLzM1NzA2NTk2NS01YWMzNTI4Ny03NWEyLTRjYjctOWViMi1kMjJjNWM3MWI2YjYuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTJUMTM1OTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE2ZmRmNjU5ZGY1Nzg0MWQ2M2UwNmIxNTc0ZGMwMDU1MWEzZDRhMTM4ZmMxZjhjYWI2MDNhNTA0ZGI3N2JmMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4jCNF3FP3P8PFnAjOHj5wNQAyFLiOyaWT-_Tlo-mq3M)

I added default input for workflow manual build that is what shows version number here, without this i cannot test build in feature branch, it could not find version release-version which is set as env variable.

2024-08-12 17:12 UTC, ErikMogensen commented
> I don't recall wherever PR build should have a version or not. @ErikMogensen do you remember?

They do not have a version number so this is correct.

2024-08-12 18:24 UTC, ErikMogensen commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
When I run: `dotnet build -c RELEASE /p:AssemblyVersion=0.1.2.3 /p:InformationalVersion=0.0.1.1` in the src directory using this branch the .NET Standard assemblies get the same Assembly version as the File version. The Assembly versions should be 1.0.0.0 on the assemblies and the File Versions should be the release version. 

The built .NET Standard assemblies lack File version and Product version. This can be checked by opening them using dotPeek. This is ServiceBusExplorer.Common:
![image](https://github.com/user-attachments/assets/eb6f1185-7a5b-489c-bcab-cdf095aae0ea)

Below is how the assembly in the latest release looks like in dotPeek :
![image](https://github.com/user-attachments/assets/0e7162d3-430d-4120-89d7-97d7dcb71cf0)

2024-08-13 09:57 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
Actually i am not able to get the versions set by dotnet build or msbuild. I will try to figure it out and update the build task

2024-08-13 09:57 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
I am 100% sure it worked last time is tested, i hope i did not  build something else :)

2024-08-13 11:00 UTC, asos-gurpreetsingh commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
I got it working using .props file for solution.
![image](https://github.com/user-attachments/assets/6cbd52f1-dfdc-4d84-8020-00df649fb1bd)

2024-08-13 11:01 UTC, asos-gurpreetsingh commented on src/ServiceBusExplorer/ServiceBusExplorer.csproj
> +	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
these are just test values i used for version, actual version will be supplied by the build task

2024-08-13 11:04 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} /p:AssemblyVersion=${{env.NUMBER_VERSION}} /p:InformationalVersion=${{inputs.release-version}}
It seems to have worked only for .netstandard projects and that was the assembly i checked. I have it working for all now.

2024-08-14 09:13 UTC, asos-gurpreetsingh commented
So what is next ? who will complete the PR ?

2024-08-14 16:18 UTC, SeanFeldman commented
> So what is next ? who will complete the PR ?

Patience. This is not paid work, and people have their own priorities :)

2024-08-14 16:25 UTC, SeanFeldman approved these changes

2024-08-14 16:25 UTC, SeanFeldman commented on src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
> +    </PackageReference>
nit: KISS
```suggestion
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    </PackageReference>
```

2024-08-14 16:25 UTC, SeanFeldman commented on src/ServiceBusExplorer.Tests/ServiceBusExplorer.Tests.csproj
>    </ItemGroup>
This can be removed, right?

```suggestion
```

2024-08-14 16:25 UTC, SeanFeldman commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} -p:GenerateAssemblyInfo=true,AssemblyVersion=${{env.NUMBER_VERSION}},InformationalVersion=${{inputs.release-version}}
This begs a unit test to validate we set the release version only if you want to add that test.

2024-08-14 16:27 UTC, SeanFeldman commented
@asos-gurpreetsingh, approved with a few suggestions. We usually try to have two reviewers on something that's a minor change. With the build version change on top of xUnit, I'll let @ErikMogensen get another pass. The good news is that this is looking good and close to completion. Thank you.

2024-08-15 10:55 UTC, asos-gurpreetsingh commented
> > So what is next ? who will complete the PR ?
> 
> Patience. This is not paid work, and people have their own priorities :)

Apologies, I did not mean to pressure, I just wanted to know what's next.

2024-08-15 11:02 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} -p:GenerateAssemblyInfo=true,AssemblyVersion=${{env.NUMBER_VERSION}},InformationalVersion=${{inputs.release-version}}
Good idea actually. I will put something in

2024-08-15 11:19 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} -p:GenerateAssemblyInfo=true,AssemblyVersion=${{env.NUMBER_VERSION}},InformationalVersion=${{inputs.release-version}}
Were you thinking about a unit test ? how would that go ?
I was thinking a unit test that check the version should be set to expected version that comes from pipeline/environment variable, but then it would fail locally because we don't have it set there.

2024-08-17 09:08 UTC, ErikMogensen commented
I tested to build this branch using `dotnet build -c RELEASE -p:GenerateAssemblyInfo=true,AssemblyVersion=0.1.2.3,InformationalVersion=0.0.1.1`. It sets File version to the same value as the Assembly version, which we don't want. Assembly version should be set per assembly. File version should be the same on all assemblies created by the build.

2024-09-13 13:41 UTC, SeanFeldman commented
@asos-gurpreetsingh, do you plan to complete this one? Erik pointed out one [last thing](https://github.com/paolosalvatori/ServiceBusExplorer/pull/801#issuecomment-2294802536) that needs attention.

2024-09-18 15:54 UTC, asos-gurpreetsingh commented
> @asos-gurpreetsingh, do you plan to complete this one? Erik pointed out one [last thing](https://github.com/paolosalvatori/ServiceBusExplorer/pull/801#issuecomment-2294802536) that needs attention.

Hi Yes I will pick this weekend, i was out on holiday

2024-09-20 09:46 UTC, asos-gurpreetsingh commented
> I tested to build this branch using `dotnet build -c RELEASE -p:GenerateAssemblyInfo=true,AssemblyVersion=0.1.2.3,InformationalVersion=0.0.1.1`. It sets File version to the same value as the Assembly version, which we don't want. Assembly version should be set per assembly. File version should be the same on all assemblies created by the build.

In your test you have used very different version numbers, if our objective is to use something like 1.2.3.0 as assembly version and 1.2.3.566 as file version then this command would do that. But if we really want to set different versions like in you example then we can use another Property "AssemblyFileVersion" for that

2024-09-21 08:10 UTC, ErikMogensen commented
Yes, we want to be able to set different versions. Thinking of this, I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline.

2024-09-21 08:10 UTC, ErikMogensen commented
There is also an issue with the build.

2024-09-21 21:08 UTC, asos-gurpreetsingh commented
> Yes, we want to be able to set different versions. Thinking of this, I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline.

Can I ask why ?

2024-09-21 22:01 UTC, asos-gurpreetsingh commented on .github/workflows/build-test.yml
> +      run: dotnet build -c ${{env.BUILD_CONFIGURATION}} -p:GenerateAssemblyInfo=true,AssemblyVersion=${{env.NUMBER_VERSION}},InformationalVersion=${{inputs.release-version}}
I have now added two unit tests to check the file version and assembly version

2024-09-21 22:17 UTC, SeanFeldman commented on src/ServiceBusExplorer.Tests/AssemblyVersionTests.cs
> +        public AssemblyVersionTests()
This is a great automated gate!

nit: It's not just an assembly version verification but an assembly and file version. Class/file name could reflect that.

2024-09-22 20:12 UTC, asos-gurpreetsingh commented on src/ServiceBusExplorer.Tests/AssemblyVersionTests.cs
> +        public AssemblyVersionTests()
now split into two files with suitable names

2024-09-23 01:04 UTC, sean-feldman-sh commented on src/ServiceBusExplorer.Tests/AssemblyVersionTests.cs
> +        public AssemblyVersionTests()
Also works 🙂

2024-09-30 20:22 UTC, ErikMogensen commented
> > Yes, we want to be able to set different versions. Thinking of this, I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline.
> 
> Can I ask why ? We could use git-version to drive version numbers.

Of course. Assembly version is used by the .NET runtime to determine and verify it is loading the intended assembly. The assembly number of a dependent assembly is stored in the manifest of the calling assembly. By default it will only load that assembly.

File version may be used for installers to determine which version an assembly has so the numbers have different purposes. 

By setting all the assemblies built in a build to have the same file version it is easy to tell for an installer and a human which build a certain assembly belongs to. Typically you do not want to change the assembly version in every build since that would make assemblies between two different builds incompatible. The exception to this if you have made changes in the assembly that lost its backward combability, then it should increase its assembly number.

Does this PR still set the assembly version to the same value on all assemblies?

2024-10-02 09:49 UTC, asos-gurpreetsingh commented
> > > Yes, we want to be able to set different versions. Thinking of this, I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline.
> > 
> > 
> > Can I ask why ? We could use git-version to drive version numbers.
> 
> Of course. Assembly version is used by the .NET runtime to determine and verify it is loading the intended assembly. The assembly number of a dependent assembly is stored in the manifest of the calling assembly. By default it will only load that assembly.
> 
> File version may be used for installers to determine which version an assembly has so the numbers have different purposes.
> 
> By setting all the assemblies built in a build to have the same file version it is easy to tell for an installer and a human which build a certain assembly belongs to. Typically you do not want to change the assembly version in every build since that would make assemblies between two different builds incompatible. The exception to this if you have made changes in the assembly that lost its backward combability, then it should increase its assembly number.
> 
> Does this PR still set the assembly version to the same value on all assemblies?

Thanks, @ErikMogensen . I understand now why one could want different versions but I am not sure we SBE uses it with that intent. But with current state of build task "dotnet build ....." allows us to use different versions for file and assembly but that will be applied to all assemblies. I don't think this we ever set up to use different file versions for each project. That can be done by setting those in the project files. Secondly if that is what we want then we can pick this up in another change and not this one.

2024-10-04 16:03 UTC, ErikMogensen commented
> Thanks, @ErikMogensen . I understand now why one could want different versions but I am not sure we SBE uses it with that intent. 
We should probably have updated the assembly numbers in some PRs.

> But with current state of build task "dotnet build ....." allows us to use different versions for file and assembly but that will be applied to all assemblies. I don't think this we ever set up to use different file versions for each project. That can be done by setting those in the project files. 
We don't want to have different file versions for assemblies in the same build so that's fine. 

> Secondly if that is what we want then we can pick this up in another change and not this one.
All work on this tool is voluntarily so there is quite a big risk that such a change will never be created. 

What is the problem with using msbuild for building?

2024-10-07 13:38 UTC, asos-gurpreetsingh commented
> > Thanks, @ErikMogensen . I understand now why one could want different versions but I am not sure we SBE uses it with that intent.
> 
> We should probably have updated the assembly numbers in some PRs.
> 
> > But with current state of build task "dotnet build ....." allows us to use different versions for file and assembly but that will be applied to all assemblies. I don't think this we ever set up to use different file versions for each project. That can be done by setting those in the project files.
> 
> We don't want to have different file versions for assemblies in the same build so that's fine.
> 
> > Secondly if that is what we want then we can pick this up in another change and not this one.
> 
> All work on this tool is voluntarily so there is quite a big risk that such a change will never be created.
> 
> What is the problem with using msbuild for building?

Apologies if I am missing something. when you say "I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline. " what is that to do with MSBuild or dotnet build ? and secondly "using a file belonging to the project of the affected assembly" sounds contradicting to "We don't want to have different file versions for assemblies". Could you please elaborate. Thanks

2024-10-11 04:46 UTC, ErikMogensen commented
> Apologies @ErikMogensen if I am missing something. when you say "I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline. " what is that to do with MSBuild or dotnet build ?

I assumed dotnet build cannot handle assembly version set in a project since you changed the way assembly versions were set. But if it is possible to set assembly versions using files belonging to each project and still use dotnet build, it would be great.

> secondly "using a file belonging to the project of the affected assembly" sounds contradicting to "We don't want to have different file versions for assemblies". Could you please elaborate. Thanks

It is about File version vs Assembly version. We want to have the same File version on all assemblies created by the build. We want Assembly version set separately for each assembly.

Just ask again if it is unclear 😄

2024-10-11 09:07 UTC, asos-gurpreetsingh commented
> > Apologies @ErikMogensen if I am missing something. when you say "I want the assembly version to be set using a file belonging to the project of the affected assembly instead of being set in the pipeline. " what is that to do with MSBuild or dotnet build ?
> 
> I assumed dotnet build cannot handle assembly version set in a project since you changed the way assembly versions were set. But if it is possible to set assembly versions using files belonging to each project and still use dotnet build, it would be great.
> 
> > secondly "using a file belonging to the project of the affected assembly" sounds contradicting to "We don't want to have different file versions for assemblies". Could you please elaborate. Thanks
> 
> It is about File version vs Assembly version. We want to have the same File version on all assemblies created by the build. We want Assembly version set separately for each assembly.
> 
> Just ask again if it is unclear.

Thanks @ErikMogensen . In that case file version can be set by dotnet build, but setting different assembly versions for each assembly would mean updating project files manually when needed. What assembly version should we set to start with ? when would it be changed (on what basis)

2024-10-12 13:05 UTC, ErikMogensen commented
> Thanks @ErikMogensen . In that case file version can be set by dotnet build, but setting different assembly versions for each assembly would mean updating project files manually when needed. 

Great!

> What assembly version should we set to start with ? 

Look with the ones that are in the main branch. (I believe all are 1.0.0,0 which is most likely not right.) Since this PR changed the .NET version, increment the major version digit (the first one). 

> when would it be changed (on what basis)

They should be increased when there is new release of the assembly with an interface that is not backwards compatible. By interface I mean, public methods, properties, interfaces, events and delegates. (I may have forgotten one or two.) Also, if the runtime requirements change I consider that a change that should increase the version number.

2024-10-20 21:06 UTC, asos-gurpreetsingh commented
@ErikMogensen I have set set the assembly versions to 1.0.0.1 in all projects and build script will provide the file version. I have updated the tests to reflect that too. Please check if this works as you expected. Could you also confirm that the publish process is not affected by this. (i have checked and it does not look like it should be affected, but please check)

2024-10-27 11:59 UTC, merged

2024-10-27 12:00 UTC, ErikMogensen commented
Well done @asos-gurpreetsingh !