Export/Import Properties of CorrelationFilter
paolosalvatori/ServiceBusExplorer pull request #812
Opened 2024-11-19 18:26 UTC by robionekenobi

In the current version, when exporting topics, the eventual properties of the CorrelationFilter of a subscription is not exported, nor imporetd
This pull requesrt correct this

2024-11-19 19:53 UTC, SeanFeldman requested changes
Thank you for the PR, @robionekenobi.
A few minor updates if you don't mind.

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +            //
```suggestion

            // We must add the Properties of the CorrelationFilter. As the Properties are not CanWrite, we must specifically add it by not testing the canWrite parameter
```

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +            //
```suggestion

            // Here we fill in the Property of the Filter CorrelationId Properties by looping through the Property Sibling
```

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                    var _read = xmlReader.ReadElementContentAsString();
Local variable don't have `_` in this code base. The underscore is reserved for member fields. Could you please rename? Thank you.

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                    _prop.Value = _read.Split(':')[1];
The split doesn't need to be happening each time. Split once and use that array parts.

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                //
```suggestion

                // We check if the CorrelationFilter has Properties.
                // If yes we write the xml <Properties><Property>A</Property></Properties>
```

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                //
```suggestion

                // We check if there is a Key with Properties
                // If Yes, we must create the properties of the CorrelationFilter
```

2024-11-19 19:53 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                //
```suggestion

                // As we already created the Properties, we must remove it here before calling SetPropertyValue, as Properties Property is ReadOnly
```

2024-11-19 20:45 UTC, robionekenobi commented on src/Common/Helpers/ImportExportHelper.cs
> +                    var _read = xmlReader.ReadElementContentAsString();
Hi, corrected and improved

2024-11-19 20:45 UTC, robionekenobi commented on src/Common/Helpers/ImportExportHelper.cs
> +                    _prop.Value = _read.Split(':')[1];
Hi, corrected and improved

2024-11-19 22:35 UTC, SeanFeldman reviewed
Two more spots and you're good 🙂

2024-11-19 22:35 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                    var _rule = ruleFilter as CorrelationFilter;
To be consistent with the project, could you remove `_` from local variables?

2024-11-19 22:35 UTC, SeanFeldman commented on src/Common/Helpers/ImportExportHelper.cs
> +                var _propVal = propertyValue.Where(p => p.Key != CorrelationFilterProperties);
Here as well.

2024-11-19 22:47 UTC, robionekenobi commented on src/Common/Helpers/ImportExportHelper.cs
> +                    var _rule = ruleFilter as CorrelationFilter;
Done

2024-11-19 22:47 UTC, robionekenobi commented on src/Common/Helpers/ImportExportHelper.cs
> +                var _propVal = propertyValue.Where(p => p.Key != CorrelationFilterProperties);
Done

2024-11-20 03:48 UTC, SeanFeldman approved these changes

2024-11-20 06:07 UTC, ErikMogensen approved these changes
Nice

2024-11-20 06:07 UTC, merged