#686: Move Topic management functions to separate class
paolosalvatori/ServiceBusExplorer pull request #818
Opened 2024-12-30 13:30 UTC by supereddie

Part 02 of refactoring the ServiceBusHelper class #686. This is a fairly straight-forward 'move code to different class' to simplify the changes.

This part is moving Topic 'management actions' - that is, actions for Topics that need the `Microsoft.ServiceBus.NamespaceManager` to work.

In addition:
- Added a base class `ServiceBusEntity` to share some code between Queue and Topic implementations.
- Changed two properties in `ServiceBusHelper` to have a `private set` to indicate it is not set from outside the class.

2024-12-30 21:54 UTC, SeanFeldman requested changes

2024-12-30 21:54 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public Task DeleteTopics(IEnumerable<string> topics)
I suggest we await here and don't return a `Task`. You don't gain a lot of performance by returning a task but you will reduce the changes of incorrect outcome.

2024-12-30 21:54 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public Task DeleteTopic(string path)
same here

2024-12-30 21:54 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public Task DeleteTopic(TopicDescription topic)
same here

2024-12-30 21:54 UTC, SeanFeldman commented on src/Common/WindowsAzure/IServiceBusQueue.cs
> +    internal interface IServiceBusQueue : IServiceBusEntity
❤️

2024-12-30 21:54 UTC, SeanFeldman commented on src/Common/WindowsAzure/ServiceBusEntity.cs
> +        }
Any reason this couldn't be an auto-property?

2024-12-31 13:18 UTC, supereddie commented on src/Common/WindowsAzure/ServiceBusEntity.cs
> +        }
Nopoe, no reason at all. I will change it.

2024-12-31 13:30 UTC, supereddie commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public Task DeleteTopics(IEnumerable<string> topics)
The main benefit I can see with returning a Task, is that you don't have to worry about `.ConfigureAwait(false)` or `.ConfigureAwait(true)` (which is default if you don't specify it) in the implementation - it can be left to the caller.

But it has been such a long time since I've done anything with Windows Forms + UI and background threads that I can't remember any 'best practices' regarding this 😆 Perhaps it is better left for a completely different issue for optimization stuff with utilizing background threads and not blocking the UI thread.

I will implement the suggestion, and see if I also did it with the previous PR for Queues and fix that at the same time.

2025-01-01 18:41 UTC, SeanFeldman commented on src/Common/Helpers/ServiceBusHelper.cs
> +        public Task DeleteTopics(IEnumerable<string> topics)
`.ConfigureAwait()` was designed so that, by default, it caters to UI-type projects where thread affinity matters. So adding `.ConfigureAwait(true)` is the same as not having it. Only for libraries does it matter to use `.ConfigureAwait(false)`. And since this code base is all about UI, you can remove `.ConfigureAwait(true)` altogether. 

A more detailed explanation is [here](https://stackoverflow.com/questions/62500130/why-is-writing-configureawaitfalse-on-every-line-with-await-always-recommended#62505101).

2025-01-01 18:43 UTC, SeanFeldman approved these changes

2025-01-01 18:43 UTC, merged